branch-defaults:
  master:
    environment: moosheadreborn-prod
global:
  application_name: mooseheadreborn
  default_ec2_keyname: javabin
  default_region: eu-central-1
  profile: javabin
  sc: git
deploy:
  artifact: app.zip